// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fdjcwslsjvqqbkesyevq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkamN3c2xzanZxcWJrZXN5ZXZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU1NDEwNjQsImV4cCI6MjA1MTExNzA2NH0.NLR_vMRMEz87tOO4hFeJQMLOC5Vl0f0bgNNxpqr8cjQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);